# Generated by Django 3.1.1 on 2020-10-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400)),
                ('option1', models.CharField(max_length=400)),
                ('option2', models.CharField(max_length=400)),
                ('option3', models.CharField(max_length=400)),
                ('option4', models.CharField(max_length=400)),
                ('correctans', models.CharField(max_length=400)),
            ],
        ),
    ]
