# Generated by Django 3.1.1 on 2020-10-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerOrganisationArchitecture', '0002_quizes_experimentno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizes',
            name='correctans',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='quizes',
            name='option2',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='quizes',
            name='option3',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='quizes',
            name='option4',
            field=models.CharField(default='', max_length=400),
        ),
    ]
