# Generated by Django 3.1.1 on 2020-10-16 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computerOrganisationArchitecture', '0003_auto_20201013_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('details', models.TextField()),
                ('happy', models.BooleanField()),
                ('date', models.DateField(auto_now_add=True)),
                ('experimentNO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computerOrganisationArchitecture.quizes')),
            ],
        ),
    ]
