# Generated by Django 3.1.1 on 2020-10-16 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computerOrganisationArchitecture', '0004_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='happy',
            new_name='satisfied',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='customer_name',
            new_name='student_name',
        ),
    ]
