# Generated by Django 3.1.1 on 2020-10-16 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computerOrganisationArchitecture', '0005_auto_20201016_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='experimentNO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computerOrganisationArchitecture.experiment'),
        ),
    ]
