# Generated by Django 3.1.1 on 2020-10-16 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computerOrganisationArchitecture', '0007_auto_20201016_1802'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
